{% set name = "rocketpy" %}
{% set version = "0.11.0" %}

package:
  name: rocketpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3358bb456022e5dabf39ab38a1aacf8174bd50b9b96dde754f0b874380dd9a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy >=1.0
    - python >=3.6
    - scipy >=1.0
    - requests

test:
  imports:
    - rocketpy

about:
  home: https://github.com/giovaniceotto/RocketPy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Advanced 6-DOF trajectory simulation for High-Power Rocketry.
  description: |
    RocketPy is a trajectory simulation for High-Power Rocketry built by
    Projeto Jupiter. The code is written as a Python library and allows
    for a complete 6 degrees of freedom simulation of a rocket's flight
    trajectory, including high fidelity variable mass effects as well as
    descent under parachutes. Weather conditions, such as wind profile,
    can be imported from sophisticated datasets, allowing for realistic
    scenarios. Furthermore, the implementation facilitates complex simulations,
    such as multi-stage rockets, design and trajectory optimization and
    dispersion analysis.
  doc_url: https://rocketpyalpha.readthedocs.io/en/latest/
  dev_url: https://github.com/giovaniceotto/RocketPy

extra:
  recipe-maintainers:
    - PatrickSampaioUSP
    - Gui-FernandesBR
    - giovaniceotto
