{% set name = "rocketpy" %}
{% set version = "0.13.0" %}

package:
  name: rocketpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3749938eac772d38ad56ddef484841f437d4c38dff3a45e335ac89de3a0858c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - matplotlib-base
    - numpy >=1.0
    - python >=3.6
    - scipy >=1.0
    - requests
    - netCDF4 >=1.4
    - windrose >=1.6.8
    - pytz
    - timezonefinder
    - simplekml
    - cftime
    - ipython
    - ipywidgets

test:
  imports:
    - rocketpy

about:
  home: https://github.com/giovaniceotto/RocketPy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Advanced 6-DOF trajectory simulation for High-Power Rocketry.
  description: |
    RocketPy is a trajectory simulation for High-Power Rocketry built by
    Projeto Jupiter. The code is written as a Python library and allows
    for a complete 6 degrees of freedom simulation of a rocket's flight
    trajectory, including high fidelity variable mass effects as well as
    descent under parachutes. Weather conditions, such as wind profile,
    can be imported from sophisticated datasets, allowing for realistic
    scenarios. Furthermore, the implementation facilitates complex simulations,
    such as multi-stage rockets, design and trajectory optimization and
    dispersion analysis.
  doc_url: https://rocketpyalpha.readthedocs.io/en/latest/
  dev_url: https://github.com/giovaniceotto/RocketPy

extra:
  recipe-maintainers:
    - PatrickSampaioUSP
    - Gui-FernandesBR
    - giovaniceotto
