{% set name = "rocketpy" %}
{% set version = "1.7.1" %}

package:
  name: rocketpy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d6dfe02a5e1b8beed2aa4609c9d9a6bae31b07e62a453c066ca57d233707518e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - numpy >=1.13
    - scipy >=1.0
    - matplotlib-base
    - netCDF4 >=1.6.4
    - requests
    - pytz
    - simplekml
    - timezonefinder
    - windrose >=1.6.8
    - IPython
    - ipywidgets >=7.6.3
    - jsonpickle

test:
  imports:
    - rocketpy

about:
  home: https://github.com/RocketPy-Team/RocketPy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Advanced 6-DOF trajectory simulation for High-Power Rocketry.
  description: |
    RocketPy is a trajectory simulation for High-Power Rocketry built by
    Projeto Jupiter. The code is written as a Python library and allows
    for a complete 6 degrees of freedom simulation of a rocket's flight
    trajectory, including high fidelity variable mass effects as well as
    descent under parachutes. Weather conditions, such as wind profile,
    can be imported from sophisticated datasets, allowing for realistic
    scenarios. Furthermore, the implementation facilitates complex simulations,
    such as multi-stage rockets, design and trajectory optimization and
    dispersion analysis.
  doc_url: https://docs.rocketpy.org/en/latest/index.html
  dev_url: https://github.com/RocketPy-Team/RocketPy

extra:
  recipe-maintainers:
    - MateusStano
    - phmbressan
    - Gui-FernandesBR
    - PatrickSampaioUSP
    - giovaniceotto
